# Generated by Django 4.2.16 on 2024-10-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_performance_user_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video_url',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Default Question', max_length=255),
        ),
    ]
